name: Release Management

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master
    tags:
      - v*

jobs:
  update_draft_release:
    name: Draft release
    runs-on: ubuntu-latest
    steps:
      # https://github.com/release-drafter/release-drafter
      - uses: release-drafter/release-drafter@v5.6.1
        env:
          # Using the action token, we would need to push a tag to the repo
          # (instead of creating one from the release interface) then connect
          # the release draft to the tag since actions cannot trigger actions.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
